### ISSUE TITLE
/emoji-data/img-apple-64/1f604.png gives 404

### ISSUE THREAD

**Issue by hacster** [needim/wdt-emoji-bundle#1]
Hi

I keep getting 404 on some images located in /emoji-data/img-apple-64/IMAGENAME.png

Can u please upload emoji.js also, it is hard to debug only in emoji.min.js

But Thanks alot for your awesome work. 

Best regards Hac

**Comment by needim** [comment]
Did you set your sheets path's?
https://github.com/needim/wdt-emoji-bundle/blob/master/demo/index.html#L210

I think you have some configuration issues.

Here is unminified version of emoji.js;
https://github.com/iamcal/js-emoji/blob/master/lib/emoji.js

**Comment by hacster** [comment]
Thanks for your reply.. Yes I did set the sheets path's

I looked at the emoji.js and found out that it was line: 
225
`var img = emoji.data[idx][7] || emoji.img_sets[emoji.img_set].path+idx+'.png';`

or / and

240
`img = emoji.img_sets[emoji.img_set].path+variation_idx+'.png';`

giving me the trouble

I did not need them so I changed to
225
`var img = emoji.data[idx][7];`
AND 
`img = '';`

By that not saying they are wrong, but in my case I dont need them. 
Thank you very much. You have been very help full
