### ISSUE TITLE
ReferenceError: emoji is not defined

### ISSUE THREAD

**Issue by NazariiStrohush** [needim/wdt-emoji-bundle#10]
I'm doing this import 
```javascript
const wdtEmojiBundle = require('/node_modules/wdt-emoji-bundle/wdt-emoji-bundle');
```
after that in code i'm doing
```javascript
wdtEmojiBundle.init('.message-input-box');
```
And it throws an error
![image](https://cloud.githubusercontent.com/assets/17307937/20919368/261607a6-bba4-11e6-9bcd-c864776b5a90.png)

How to properly import this package from NodeJS?

**Comment by Exponent500** [comment]
Can someone answer this? I'm having the same problem.

**Comment by needim** [comment]
You can find emoji.min.js in this repo. It's my mistake, I forgot the mention about that, sorry guys :/
