### ISSUE TITLE
emoji.min.js error on chrome v 55.0.2883.8

### ISSUE THREAD

**Issue by remyam** [needim/wdt-emoji-bundle#11]
On the latest version of chrome (Version 55.0.2883.87 m, windows) I am getting this error on emoji.min.js -
"Uexpected identifier".

This causes emojis to break. Can someone please provide a solution?

**Comment by needim** [comment]
Can you try with https://github.com/iamcal/js-emoji/blob/master/lib/emoji.min.js

**Comment by remyam** [comment]
Worked for me. Thank you so much. Just made few changes to make it compatible with wdt-emoji-bundle.js. What was the issue here?

**Comment by needim** [comment]
I'm not sure, I don't have an environment to test it right now but I will update the repo for latest emoji.min.js soon. Thanks for reporting.

**Comment by nageshd3** [comment]
@remyam Can you tell me what are the changes you made in wdt-emoji-bundle.js. I'm trying to figure out why it's not working. Although changing to the above link (emoji.min.js) resolved 1 error, another one is still there. It says 'Uncaught ReferenceError: emoji is not defined'.
Thanks.
