### ISSUE TITLE
sticky tabs bug - widget scrolls all the way to the bottom

### ISSUE THREAD

**Issue by dylanjha** [needim/wdt-emoji-bundle#18]
As far as I know this did not happen before, but it does now and I have not updated versions. Maybe something in chrome changed?

See in the gif from the demo page that when clicking some of the tabs the widget scrolls all the way to the bottom. I spent a long time debugging this but was not able to find a solution.

![screen recording 2017-03-07 at 04 53 pm](https://cloud.githubusercontent.com/assets/764988/23685015/c611fbf8-0356-11e7-8d02-446f1cec1754.gif)

**Comment by Daniel900318** [comment]
same here, help me

**Comment by needim** [comment]
weird, for quick fix delete sticky function calls at https://github.com/needim/wdt-emoji-bundle/blob/master/wdt-emoji-bundle.js#L341

I will take a look later in this month, currently a little bit busy.

**Comment by Daniel900318** [comment]
try it like follow

on line 627
# css(el.parentNode, {'padding-top': el.getBoundingClientRect().height + 'px'});

maybe works well

**Comment by ryantgraham** [comment]
This is because of Scroll Anchoring that was introduced as an experimental feature in Chrome 51:
https://developers.google.com/web/updates/2016/04/scroll-anchoring

and then enabled by default in Chrome 56:
https://www.chromestatus.com/feature/5700102471548928

This can be fixed by adding `overflow-anchor: none;` to `.wdt-emoji-scroll-wrapper`.

**Comment by dylanjha** [comment]
@ryantgraham very good find 🔎 🕵️

**Comment by Redsandro** [comment]
Good find indeed. @needim doesn't need to investigate.

**Comment by dylanjha** [comment]
I'll push up a fix for this

**Comment by fLooojava** [comment]
adding the line "overflow-anchor: none;" makes no difference under chrome 57. is there any new fix for this known bug? 😢
