### ISSUE TITLE
An error in the documentation?

### ISSUE THREAD

**Issue by Motherships** [needim/wdt-emoji-bundle#29]
Documentation says: 

> Set emoji set default sheet
> 
> `wdtEmojiBundle.defaults.type = 'emojione';`

This didnt work for me

Instead i used 

> `wdtEmojiBundle.defaults.emojiType = 'emojione';`

**Comment by lolgans** [comment]
created a fork for a readme update

**Comment by needim** [comment]
Thanks, merged 👍
