### ISSUE TITLE
Wrong short name for emoji `snowman`

### ISSUE THREAD

**Issue by christophemaximin** [needim/wdt-emoji-bundle#5]
In `wdt-emoji-bundle.js`: `{"has_img_apple":true,"has_img_google":true,"has_img_twitter":true,"has_img_emojione":false,"name":"SNOWMAN","short_name":"showman","short_names":["showman"],"sort_order":137}`

`name: SNOWMAN`
`short_name: showman`

EDIT:
Turns out the emoji snowman (as SNOWMAN WITHOUT SNOW) is already present, the showman (as SNOWMAN) is a duplicate which should be deleted.

**Comment by christophemaximin** [comment]
Turns out the emoji `snowman` (as SNOWMAN WITHOUT SNOW) is already present, the `showman` (as SNOWMAN) is a duplicate which should be deleted.

**Comment by needim** [comment]
Related #25
